name: wisewidgetslibrary
description: Wisemen widgets library containing platform specific widgets and other commonly useful widgets.
version: 1.0.28
homepage: https://github.com/wisemen-digital/flutter-widgets-library
repository: https://github.com/wisemen-digital/flutter-widgets-library

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=2.19.7"


dependencies:
  # Flutter
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # Data
  json_annotation: ^4.8.1

  # Images
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  flutter_svg: ^2.0.10+1

  # UI
  auto_size_text: ^3.0.0
  pull_down_button: ^0.10.2
  sliver_tools: ^0.2.12
  
  # Extensions
  collection: ^1.18.0
  
  # Validation
  email_validator: ^3.0.0

  # Riverpod
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Animations
  page_transition: ^2.1.0

  # Conditional wrap
  conditional_wrap: ^3.0.0

  # Image carousel
  dismissible_page: ^1.0.2
  flutter_hooks: ^0.20.5

dev_dependencies:
  # Code generation
  build_runner: ^2.4.13

  # Testing
  flutter_test:
    sdk: flutter

  # Static analysis & linting
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.0
  dependency_validator: ^4.1.1

  # Data
  json_serializable: ^6.7.1

  # Riverpod
  riverpod_generator: ^2.6.2

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

  plugin:
    platforms:
      ios:
        pluginClass: WiseWidgetsLibraryPlugin

