name: wisewidgetslibrary
description: Wisemen widgets library containing platform specific widgets and other commonly useful widgets.
version: 1.0.3
homepage: https://github.com/wisemen-digital/flutter-widgets-library
repository: https://github.com/wisemen-digital/flutter-widgets-library

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=2.19.7"

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  collection: ^1.18.0
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  hooks_riverpod: ^2.4.5
  intl: ^0.18.1
  json_annotation: ^4.8.1
  page_transition: ^2.1.0
  photo_view: ^0.14.0
  pull_down_button: ^0.9.3
  riverpod_annotation: ^2.1.1
  sliver_tools: ^0.2.12

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  riverpod_generator: ^2.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

  plugin:
    platforms:
      ios:
        pluginClass: WiseWidgetsLibraryPlugin

